package com.juagri.shared.utils.theme
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF38B91B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF8FFA98)
val md_theme_light_onPrimaryContainer = Color(0xFF002107)
val md_theme_light_secondary = Color(0xFF01A9DE)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFBCE9FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F2A)
val md_theme_light_tertiary = Color(0xFF39656C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBCEBF2)
val md_theme_light_onTertiaryContainer = Color(0xFF001F23)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF1A1C19)
val md_theme_light_surface = Color(0xFFFCFDF7)
val md_theme_light_onSurface = Color(0xFF1A1C19)
val md_theme_light_surfaceVariant = Color(0xFFDEE5D9)
val md_theme_light_onSurfaceVariant = Color(0xFF424940)
val md_theme_light_outline = Color(0xFF72796F)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1EB)
val md_theme_light_inverseSurface = Color(0xFF2F312D)
val md_theme_light_inversePrimary = Color(0xFF73DD7F)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006E27)
val md_theme_light_outlineVariant = Color(0xFFC2C9BD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF73DD7F)
val md_theme_dark_onPrimary = Color(0xFF003911)
val md_theme_dark_primaryContainer = Color(0xFF00531C)
val md_theme_dark_onPrimaryContainer = Color(0xFF8FFA98)
val md_theme_dark_secondary = Color(0xFF63D3FF)
val md_theme_dark_onSecondary = Color(0xFF003545)
val md_theme_dark_secondaryContainer = Color(0xFF004D63)
val md_theme_dark_onSecondaryContainer = Color(0xFFBCE9FF)
val md_theme_dark_tertiary = Color(0xFFA1CED6)
val md_theme_dark_onTertiary = Color(0xFF00363C)
val md_theme_dark_tertiaryContainer = Color(0xFF1F4D53)
val md_theme_dark_onTertiaryContainer = Color(0xFFBCEBF2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C19)
val md_theme_dark_onBackground = Color(0xFFE2E3DD)
val md_theme_dark_surface = Color(0xFF1A1C19)
val md_theme_dark_onSurface = Color(0xFFE2E3DD)
val md_theme_dark_surfaceVariant = Color(0xFF424940)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C9BD)
val md_theme_dark_outline = Color(0xFF8C9389)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C19)
val md_theme_dark_inverseSurface = Color(0xFFE2E3DD)
val md_theme_dark_inversePrimary = Color(0xFF006E27)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF73DD7F)
val md_theme_dark_outlineVariant = Color(0xFF424940)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF1A9E0B)
val text = Color(0xFF636464)
val textTitle = Color(0xFF222222)
val textHint = Color(0xFFC0C0C0)
val light_text = Color(0xFF006971)
val light_ontext = Color(0xFFFFFFFF)
val light_textContainer = Color(0xFF82F3FF)
val light_ontextContainer = Color(0xFF002022)
val dark_text = Color(0xFF4DD9E6)
val dark_ontext = Color(0xFF00363B)
val dark_textContainer = Color(0xFF004F55)
val dark_ontextContainer = Color(0xFF82F3FF)
val light_textTitle = Color(0xFF006874)
val light_ontextTitle = Color(0xFFFFFFFF)
val light_textTitleContainer = Color(0xFF97F0FF)
val light_ontextTitleContainer = Color(0xFF001F24)
val dark_textTitle = Color(0xFF4FD8EB)
val dark_ontextTitle = Color(0xFF00363D)
val dark_textTitleContainer = Color(0xFF004F58)
val dark_ontextTitleContainer = Color(0xFF97F0FF)
val light_textHint = Color(0xFF006874)
val light_ontextHint = Color(0xFFFFFFFF)
val light_textHintContainer = Color(0xFF97F0FF)
val light_ontextHintContainer = Color(0xFF001F24)
val dark_textHint = Color(0xFF4FD8EB)
val dark_ontextHint = Color(0xFF00363D)
val dark_textHintContainer = Color(0xFF004F58)
val dark_ontextHintContainer = Color(0xFF97F0FF)

val light_screenBackground = Color(0xFFF5F5F5)
val dark_screenBackground = Color(0xFF636363)

val ColorScheme.chart_os_l90: Color get() = Color(0xFF05AE99)
val ColorScheme.chart_os_l120: Color get() = Color(0xFF7C4DFF)
val ColorScheme.chart_os_l180: Color get() = Color(0xFFE69103)
val ColorScheme.chart_os_g180: Color get() = Color(0xFFFE5250)
val ColorScheme.chart_os_total: Color get() = Color.Transparent
val ColorScheme.chart_m_plan_start: Color get() = Color(0xFFD8E2E1)
val ColorScheme.chart_m_plan_end: Color get() = Color(0xFFD8E2E1)
val ColorScheme.chart_y_plan_start: Color get() = Color(0xFFD8E2E1)
val ColorScheme.chart_y_plan_end: Color get() = Color(0xFFD8E2E1)
val ColorScheme.chart_m_actual_start: Color get() = Color(0xFF214C7C)
val ColorScheme.chart_m_actual_end: Color get() = Color(0xFF96B1CE)
val ColorScheme.chart_y_actual_start: Color get() = Color(0xFF198165)
val ColorScheme.chart_y_actual_end: Color get() = Color(0xFF7CB8A8)
val ColorScheme.ledger_invoice: Color get() = Color(0xFF429C93)
val ColorScheme.ledger_cheque: Color get() = Color(0xFF378AB4)

@Composable
fun ColorScheme.screenBackground(): Color
    = if (isSystemInDarkTheme()) dark_screenBackground else light_screenBackground
