package com.juagri.shared.utils.strings

object EN_Names: Names {
    override val login: String get() = "Login"
    override val otp: String get() = "Otp"
    override val home: String get() = "Home"
    override val dashboard: String get() = "Dashboard"
    override val region: String get() = "Region"
    override val territory: String get() = "Territory"
    override val dealer: String get() = "Dealer"
    override val finYear: String get() = "Fin Year"
    override val finMonth: String get() = "Fin Month"
    override val submit: String get() = "Submit"
    override val cancel: String get() = "Cancel"
    override val select: String get() = "Select"
    override val mobileNumber: String get() = "Mobile Number"
    override val pleaseSelectValidRegion: String get() = "Please select region"
    override val pleaseSelectValidTerritory: String get() = "Please select territory"
    override val pleaseSelectValidDealer: String get() = "Please select dealer"
    override val pleaseSelectValidFinYear: String get() = "Please select financial year"
    override val pleaseSelectValidFinMonth: String get() = "Please select financial year"
    override val openingBalance: String get() = "Opening Balance"
    override val closingBalance: String get() = "Closing Balance"
    override val debit: String get() = "Debit"
    override val credit: String get() = "Credit"
    override val balance: String get() = "Balance"
    override val invoiceNo: String get() = "Invoice No"
    override val chequeNo: String get() = "Cheque No"
    override val all: String get() = "All"
    override val dealerLedger: String get() = "Dealer Ledger"
    override val menu: String get() = "Menu"
    override val services: String get() = "Service"
    override val weather: String get() = "Weather"
    override val user: String get() = "User"
    override val profile: String get() = "Profile"
    override val onlineOrder: String get() = "Online Order"
    override val yourOrders: String get() = "Your Orders"
    override val juDoctor: String get() = "JU Doctor"
    override val devices: String get() = "Devices"
    override val name: String get() = "Name"
    override val employeeCode: String get() = "Employee Code"
    override val role: String get() = "Role"
    override val appVersion: String get() = "App Version"
    override val logout: String get() = "Logout"
    override val selectEvent: String get() = "Select Activity"
    override val event: String get() = "Event"
    override val district: String get() = "District"
    override val village: String get() = "Village"
    override val promotionActivity: String get() = "Promotion Activity"
    override val promotionEntriesList: String get() = "Promotion Entries List"
    override val focusProduct: String get() = "Focus Products"
    override val monthPlan: String get() = "Month Plan"
    override val monthActual: String get() = "Month Actual"
    override val yearPlan: String get() = "Year Plan"
    override val yearActual: String get() = "Year Actual"
    override val liquidation: String get() = "Liquidation"
    override val qty: String get() = "Qty"
    override val amount: String get() = "Amount"

    override val loginInfo: String get() = "Login Info"


    override val selectRegion: String get() = "$select $region"
    override val selectTerritory: String get() = "$select $territory"
    override val selectDealer: String get() = "$select $dealer"
    override val selectFinYear: String get() = "$select $finYear"
    override val selectFinMonth: String get() = "$select $finMonth"
}