package com.juagri.shared.utils.strings

object HI_Names: Names {
    override val login: String get() = "लॉग इन करें"
    override val otp: String get() = "ओ टी पी"
    override val home: String get() = "घर"
    override val dashboard: String get() = "डैशबोर्ड"
    override val region: String get() = "क्षेत्र"
    override val territory: String get() = "इलाका"
    override val dealer: String get() = "विक्रेता"
    override val finYear: String get() = "वित्तीय वर्ष"
    override val finMonth: String get() = "वित्तीय माह"
    override val submit: String get() = "जमा करना"
    override val cancel: String get() = "रद्द करना"
    override val select: String get() = "चुनना"
    override val mobileNumber: String get() = "मोबाइल नंबर"
    override val pleaseSelectValidRegion: String get() = "कृपया क्षेत्र चुनें"
    override val pleaseSelectValidTerritory: String get() = "कृपया क्षेत्र चुनें"
    override val pleaseSelectValidDealer: String get() = "कृपया डीलर का चयन करें"
    override val pleaseSelectValidFinYear: String get() = "कृपया वित्तीय वर्ष चुनें"
    override val pleaseSelectValidFinMonth: String get() = "कृपया वित्तीय माह चुनें"
    override val openingBalance: String get() = "प्रारंभिक जमा"
    override val closingBalance: String get() = "जमा शेष"
    override val debit: String get() = "डेबिट"
    override val credit: String get() = "श्रेय"
    override val balance: String get() = "संतुलन"
    override val invoiceNo: String get() = "चालान नंबर"
    override val chequeNo: String get() = "चेक नं"
    override val all: String get() = "सभी"
    override val dealerLedger: String get() = "डीलर बही"
    override val menu: String get() = "मेन्यू"
    override val services: String get() = "सेवा"
    override val weather: String get() = "मौसम"
    override val user: String get() = "उपयोगकर्ता"
    override val profile: String get() = "प्रोफ़ाइल"
    override val onlineOrder: String get() = "ऑनलाइन ऑर्डर"
    override val yourOrders: String get() = "तुम्हारे ऑर्डर"
    override val juDoctor: String get() = "जेयू डॉक्टर"
    override val devices: String get() = "उपकरण"

    override val selectRegion: String get() = "$select $region"
    override val selectTerritory: String get() = "$select $territory"
    override val selectDealer: String get() = "$select $dealer"
    override val selectFinYear: String get() = "$select $finYear"
    override val selectFinMonth: String get() = "$select $finMonth"
}