package com.juagri.shared.utils.strings

interface Names {
    val login: String
    val otp: String
    val home: String
    val dashboard: String
    val region: String
    val territory: String
    val dealer: String
    val finYear: String
    val finMonth: String
    val submit: String
    val cancel: String
    val select: String
    val mobileNumber: String
    val pleaseSelectValidRegion: String
    val pleaseSelectValidTerritory: String
    val pleaseSelectValidDealer: String
    val pleaseSelectValidFinYear: String
    val pleaseSelectValidFinMonth: String
    val openingBalance: String
    val closingBalance: String
    val debit: String
    val credit: String
    val balance: String
    val invoiceNo: String
    val chequeNo: String
    val all: String
    val dealerLedger: String
    val menu: String
    val services: String
    val weather: String
    val user: String
    val profile: String
    val onlineOrder: String
    val yourOrders: String
    val juDoctor: String
    val devices: String
    val name: String
    val employeeCode: String
    val role: String
    val appVersion: String
    val logout: String

    val selectRegion: String
    val selectTerritory: String
    val selectDealer: String
    val selectFinYear: String
    val selectFinMonth: String
}