package com.juagri.shared.utils.strings

object TN_Names: Names {
    override val login: String get() = "உள்நுழைய"
    override val otp: String get() = "ஓடிபி"
    override val home: String get() = "வீடு"
    override val dashboard: String get() = "டாஷ்போர்டு"
    override val region: String get() = "பிராந்தியம்"
    override val territory: String get() = "பிரதேசம்"
    override val dealer: String get() = "வியாபாரி"
    override val finYear: String get() = "நிதி ஆண்டு"
    override val finMonth: String get() = "நிதி மாதம்"
    override val submit: String get() = "சமர்ப்பிக்கவும்"
    override val cancel: String get() = "ரத்து செய்"
    override val select: String get() = "தேர்ந்தெடு"
    override val mobileNumber: String get() = "மொபைல் எண்"
    override val pleaseSelectValidRegion: String get() = "தயவுசெய்து பிராந்தியத்தைத் தேர்ந்தெடுக்கவும்"
    override val pleaseSelectValidTerritory: String get() = "தயவுசெய்து பிரதேசத்தைத் தேர்ந்தெடுக்கவும்"
    override val pleaseSelectValidDealer: String get() = "தயவுசெய்து டீலரைத் தேர்ந்தெடுக்கவும்"
    override val pleaseSelectValidFinYear: String get() = "தயவுசெய்து நிதி ஆண்டைத் தேர்ந்தெடுக்கவும்"
    override val pleaseSelectValidFinMonth: String get() = "தயவுசெய்து நிதி மாதத்தைத் தேர்ந்தெடுக்கவும்"
    override val openingBalance: String get() = "ஆரம்ப இருப்பு"
    override val closingBalance: String get() = "நிறைவு இருப்பு"
    override val debit: String get() = "டெபிட்"
    override val credit: String get() = "கடன்"
    override val balance: String get() = "இருப்பு"
    override val invoiceNo: String get() = "இன்வாய்ஸ் எண்"
    override val chequeNo: String get() = "காசோலை எண்"
    override val all: String get() = "அனைத்தும்"
    override val dealerLedger: String get() = "டீலர் லெட்ஜர்"
    override val menu: String get() = "மெனு"
    override val services: String get() = "சேவைகள்"
    override val weather: String get() = "வானிலை"
    override val user: String get() = "பயனர்"
    override val profile: String get() = "சுயவிவரம்"
    override val onlineOrder: String get() = "ஆன்லைன் ஆர்டர்"
    override val yourOrders: String get() = "உங்கள் ஆர்டர்கள்"
    override val juDoctor: String get() = "ஜேயூ டாக்டர்"
    override val devices: String get() = "சாதனங்கள்"
    override val name: String get() = "பெயர்"
    override val employeeCode: String get() = "பணியாளர் குறியீடு"
    override val role: String get() = "பங்கு"
    override val appVersion: String get() = "ஆப் பதிப்பு"
    override val logout: String get() = "வெளியேறு"

    override val selectRegion: String get() = "$select $region"
    override val selectTerritory: String get() = "$select $territory"
    override val selectDealer: String get() = "$select $dealer"
    override val selectFinYear: String get() = "$select $finYear"
    override val selectFinMonth: String get() = "$select $finMonth"
}